// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuj0-6LveRzTcAKpcoA087Onyx_ZFhTnY',
    appId: '1:398053493092:android:837175139e0936358d5271',
    messagingSenderId: '398053493092',
    projectId: 'amad-shop-billing-2c68c',
    storageBucket: 'amad-shop-billing-2c68c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZEG3bmkJIaK3Ui5INnVteVkqfac02dDU',
    appId: '1:398053493092:ios:17dea2bac871c1908d5271',
    messagingSenderId: '398053493092',
    projectId: 'amad-shop-billing-2c68c',
    storageBucket: 'amad-shop-billing-2c68c.firebasestorage.app',
    iosBundleId: 'com.amadshop.billingApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2wT-o7xStKKQy_sFmsWruwzIpTw0Sng',
    appId: '1:398053493092:web:f27d4ca3c6f28f048d5271',
    messagingSenderId: '398053493092',
    projectId: 'amad-shop-billing-2c68c',
    authDomain: 'amad-shop-billing-2c68c.firebaseapp.com',
    storageBucket: 'amad-shop-billing-2c68c.firebasestorage.app',
    measurementId: 'G-X8YDZ2MGLS',
  );
}
